sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t esahakian/multi-docker-client-test -f ./client/Dockerfile.dev ./client
    # - docker build -t esahakian/docker-react .

script:
    - docker run -e CI=true esahakian/multi-docker-client-test npm run test

after_success:
    - docker build -t esahakian/multi-docker-client ./client
    - docker build -t esahakian/multi-docker-nginx ./nginx
    - docker build -t esahakian/multi-docker-server ./server
    - docker build -t esahakian/multi-docker-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take thoes images and push them to docker hub
    - docker push esahakian/multi-docker-client
    - docker push esahakian/multi-docker-nginx
    - docker push esahakian/multi-docker-server
    - docker push esahakian/multi-docker-worker
      # deploy:
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
#     edge: true
#     provider: elasticbeanstalk
#     region: 'us-east-2'
#     app: 'docker-react'
#     env: 'DockerReact-env'
#     bucket_name: 'elasticbeanstalk-us-east-2-612756466101'
#     bucket_path: 'docker-react'
#     on:
#         branch: master
